version: '3.1'

services:
  haproxy:
    image: haproxy:2.7.8-bullseye
    ports:
      - 80:80
      - 443:443
      - 1936:1936
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./ssl:/usr/local/etc/haproxy/certs
  memcached:
    image: memcached:1.6-alpine
  lists:
    image: nginx:1.24.0-alpine
    env_file:
      - lists.env
    volumes:
      - ./templates/lists:/etc/nginx/templates
      - ./ovr_lists:/var/www/html
  php8.2:
    build: ./php8.2
    env_file:
      - lists.env
    volumes:
      - ./ovr_lists:/var/www/html
  php7.1:
    build: ./php7.1
    env_file:
      - lists.env
    volumes:
      - ./ovr_lists:/var/www/html
  web:
    image: nginx:1.24.0-alpine
    env_file:
      - nginx.env
      - wordpress.env
    volumes:
      - ./templates/nginx:/etc/nginx/templates
      - wordpress:/var/www/html
      - ./ovrride/wp-content:/var/www/html/wp-content
  wordpress:
    build: ./ovr-wordpress
    restart: always
    env_file:
      - ./wordpress.env
    volumes:
      - wordpress:/var/www/html
      - ./ovrride/wp-content:/var/www/html/wp-content
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - nginx.env
      - wordpress.env
    volumes:
      - db:/var/lib/mysql
      - ./sql/ovrride.sql:/docker-entrypoint-initdb.d/01-ovrride.sql
      - ./sql/dev.sql:/docker-entrypoint-initdb.d/02-dev.sql
volumes:
  wordpress:
  db: