FROM php:8.1-fpm-alpine
RUN /usr/local/bin/docker-php-source extract
RUN apk update && apk upgrade && apk add brotli brotli-libs sqlite-dev \
git \
freetype-dev \
libjpeg-turbo-dev \
libpng-dev \
ldb-dev \
imagemagick-dev \
libldap \
oniguruma \
oniguruma-dev \
openldap-dev \
zlib-dev \
libzip-dev \
libmemcached-dev \
libxml2-dev  \
g++ \
make  \
autoconf \
vips-dev \
php81-pecl-imagick \
libwebp-dev 

RUN docker-php-ext-configure gd  --with-freetype --with-webp --with-jpeg  && \
docker-php-ext-install exif gd ldap mbstring mysqli pdo_mysql pdo_sqlite zip soap && \
pecl channel-update pecl.php.net && \
pecl install memcached vips && docker-php-ext-enable memcached vips && \
docker-php-source delete
RUN cd /tmp && \
git clone https://github.com/kjdev/php-ext-brotli.git  && \
cd php-ext-brotli && \
phpize && \
./configure --with-libbrotli && \
make && \
make install && \
echo "extension=brotli" >> /usr/local/etc/php/conf.d/brotli.ini 

# Setup timezone to Eastern Standard Time, max upload size to 100M and sessions to redis
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini  && \
sed -i'' 's/^;\(date.timezone.*\)/\1 \"America\/New_York"/' /usr/local/etc/php/php.ini  && \
sed -i'' 's/memory_limit.*=.*128M/memory_limit = 512M/' /usr/local/etc/php/php.ini  && \
sed -i'' 's/max_execution_time.*=.*30/max_execution_time = 60/' /usr/local/etc/php/php.ini  && \
sed -i'' 's/^\(upload_max_filesize\s*=\s*\).*\$/\1100M/' /usr/local/etc/php/php.ini  && \
sed -i'' 's/^\(post_max_size\s*=\s*\).*\$/\1100M/' /usr/local/etc/php/php.ini  && \
sed -i'' 's/^session.save_handler.*$/session.save_handler = memcached/' /usr/local/etc/php/php.ini  && \
sed -i'' "s/^;session.save_path.*/session.save_path = 'memcached:11211'/" /usr/local/etc/php/php.ini  && \
sed -i'' 's/^pm.max_children.*/pm.max_children = 20/' /usr/local/etc/php-fpm.d/www.conf  && \
/usr/local/bin/docker-php-source delete

