FROM wordpress:6.2.2-fpm
RUN /usr/local/bin/docker-php-source extract

# Install other needed extensions
#RUN apt-get update && apt-get install -y libsqlite3-dev libfreetype6 libjpeg62-turbo libmcrypt4 libpng16-16 sendmail --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN buildDeps=" \
        libsqlite3-dev \
        libfreetype6 \
        libjpeg62-turbo \
        libpng16-16 \
        sendmail \
		libfreetype6-dev \
		libjpeg-dev \
		libldap2-dev \
		libpng-dev \
		zlib1g-dev \
        libonig-dev \
        libzip-dev \
        libmemcached-dev \
        libxml2-dev \
	"; \
	set -x \
	&& apt update && apt install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* 

    RUN docker-php-ext-configure gd  --with-jpeg=/usr/include  --with-freetype=/usr/include 
	RUN docker-php-ext-install gd intl ldap mbstring mysqli pdo_mysql pdo_sqlite zip soap
    RUN pecl install memcached && docker-php-ext-enable memcached
    RUN docker-php-source delete
    # Setup timezone to Eastern Standard Time, max upload size to 100M and sessions to redis
    RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
    RUN sed -i'' 's/^;\(date.timezone.*\)/\1 \"America\/New_York"/' /usr/local/etc/php/php.ini && \
    sed -i'' 's/^\(upload_max_filesize\s*=\s*\).*\$/\1100M/' /usr/local/etc/php/php.ini && \
    sed -i'' 's/^\(post_max_size\s*=\s*\).*\$/\1100M/' /usr/local/etc/php/php.ini && \
    sed -i'' 's/^session.save_handler.*$/session.save_handler = memcached/' /usr/local/etc/php/php.ini && \
    sed -i'' "s/^;session.save_path.*/session.save_path = 'tcp:\/\/memcached:11211'/" /usr/local/etc/php/php.ini && \
    sed -i'' 's/^pm.max_children.*/pm.max_children = 20/' /usr/local/etc/php-fpm.d/www.conf && \
    /usr/local/bin/docker-php-source delete