FROM wordpress:6.3.2-fpm

RUN buildDeps=" \
    brotli \
    git \
    libbrotli-dev \
    libsqlite3-dev \
    libfreetype6 \
    libjpeg62-turbo \
    libpng16-16 \
    sendmail \
    libfreetype6-dev \
    libjpeg-dev \
    libldap2-dev \
    libpng-dev \
    zlib1g-dev \
    libonig-dev \
    libzip-dev \
    libmemcached-dev \
    libxml2-dev \
    libwebp-dev \
	"; \
set -x \
&& apt update && apt install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* 

RUN cd /tmp && \
git clone https://github.com/kjdev/php-ext-brotli.git  && \
cd php-ext-brotli && \
phpize && \
./configure --with-libbrotli && \
make && \
make install && \
echo "extension=brotli" >> /usr/local/etc/php/conf.d/brotli.ini 

RUN /usr/local/bin/docker-php-source extract && \
docker-php-ext-configure gd  --with-freetype --with-webp --with-jpeg && \
docker-php-ext-install gd intl ldap mbstring mysqli pdo_mysql pdo_sqlite zip soap && \
pecl install memcached && docker-php-ext-enable memcached && \
docker-php-source delete && \
cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini && \
sed -i'' 's/^;\(date.timezone.*\)/\1 \"America\/New_York"/' /usr/local/etc/php/php.ini && \
sed -i'' 's/^\(upload_max_filesize\s*=\s*\).*\$/\1100M/' /usr/local/etc/php/php.ini && \
sed -i'' 's/^\(post_max_size\s*=\s*\).*\$/\1100M/' /usr/local/etc/php/php.ini && \
sed -i'' 's/^session.save_handler.*$/session.save_handler = memcached/' /usr/local/etc/php/php.ini && \
sed -i'' "s/^;session.save_path.*/session.save_path = 'tcp:\/\/memcached:11211'/" /usr/local/etc/php/php.ini && \
sed -i'' 's/^pm.max_children.*/pm.max_children = 20/' /usr/local/etc/php-fpm.d/www.conf && \
/usr/local/bin/docker-php-source delete